# Copyright 2021 John Harwell, All rights reserved.
#
#  SPDX-License-Identifier: MIT
#
"""
Classes for generating graphs within a single experiment in a batch.
"""

# Core packages
import typing as tp

# 3rd party packages
from sierra.core.pipeline import stage4
from sierra.core import types

# Project packages
from titerra.projects.common.pipeline.stage4.flexibility_plots import FlexibilityPlotsCSVGenerator
from titerra.projects.common.pipeline.stage4.flexibility_plots import FlexibilityPlotsDefinitionsGenerator
import titerra.variables.batch_criteria as bc


class IntraExpGraphGenerator(stage4.intra_exp_graph_generator.IntraExpGraphGenerator):
    """
    Extends :class:`~sierra.core.pipeline.stage4.intra_exp_graph_generator.IntraExpGraphGenerator`
    with additional graphs for the COMMON project.
    """

    def __call__(self, criteria: bc.IConcreteBatchCriteria) -> None:
        """
        In addition to the graphs generated by
        :class:`~sierra.core.pipeline.stage4.intra_exp_graph_generator.IntraExpGraphGenerator`,
        run the following to generate graphs within each experiment in the
        batch:

        - If ``--gen-vc-plots`` was passed, generated variance curve plots.
        """
        if self.cmdopts['gen_vc_plots'] and criteria.is_univar():
            self.logger.info('Flexibility plots from %s',
                             self.cmdopts['exp_output_root'])
            FlexibilityPlotsCSVGenerator(self.main_config,
                                         self.cmdopts)(criteria)

        LN_targets, HM_targets = self.calc_targets()
        self.generate(LN_targets, HM_targets)

    def calc_targets(self) -> tp.Tuple[tp.List[types.YAMLDict],
                                       tp.List[types.YAMLDict]]:
        """
        Add graphs for --gen-vc-plots to set of graphs to generate.
        """
        LN_targets, HM_targets = super().calc_targets()

        if self.cmdopts['gen_vc_plots']:  # optional
            self.logger.debug("Add graphs for flexibility plots")
            extra_graphs = FlexibilityPlotsDefinitionsGenerator()()
            LN_targets.append({'graphs': extra_graphs})

        return LN_targets, HM_targets


__api__ = ['IntraExpGraphGenerator']
