base_graphs: &base_graphs
  - LN_spatial_interference
  - LN_spatial_movement
  - LN_spatial_nest_zone
  - LN_block_trans
  - LN_block_acq
  - LN_block_manip
  # - LN_convergence
  # - LN_perception
  # - LN_population
  - HM_arena
  - HM_swarm

d0:
  xml:
    attr_change:
      - ['.//loop_functions', 'label', 'd0_loop_functions']
      - ['.//qt-opengl/user_functions', 'label', 'd0_qt_user_functions']
  controllers:
    - name: CRW
      xml:
        tag_change:
          - ['.//controllers', '__CONTROLLER__', 'crw_controller']

      graphs_inherit:
        - *base_graphs
    - name: &DPO DPO
      xml:
        tag_change:
          - ['.//controllers', '__CONTROLLER__', 'dpo_controller']
      graphs_inherit:
        - *base_graphs
      graphs: &DPO_graphs
        - LN_perception
    - name: &ODPO ODPO
      xml:
        tag_change:
          - ['.//controllers', '__CONTROLLER__', 'odpo_controller']
      graphs_inherit:
        - *base_graphs
        - *DPO_graphs
    - name: &MDPO MDPO
      xml:
        tag_change:
          - ['.//controllers', '__CONTROLLER__', 'mdpo_controller']
      graphs_inherit:
        - *base_graphs
        - *DPO_graphs
    - name: &OMDPO OMDPO
      xml:
        tag_change:
          - ['.//controllers', '__CONTROLLER__', 'omdpo_controller']
      graphs_inherit:
        - *base_graphs
        - *DPO_graphs

d1:
  xml:
    attr_change:
      - ['.//loop_functions', 'label', 'd1_loop_functions']
      - ['.//qt-opengl/user_functions', 'label', 'd1_qt_user_functions']
      - ['.//cache_sel_matrix/pickup_policy', 'policy', 'Null' ]
      - ['.//task_partition/src_sigmoid_sel/sigmoid_sel/sigmoid', 'reactivity', '4.0' ]
      - ['.//task_partition/src_sigmoid_sel/sigmoid_sel/sigmoid', 'gamma', '1.75' ]
      - ['.//subtask_sel/src_sigmoid_sel/sigmoid_sel/sigmoid', 'reactivity', '0.5' ]
      - ['.//subtask_sel/src_sigmoid_sel/sigmoid_sel/sigmoid', 'gamma', '0.75' ]

  controllers:
    - name: BITD_DPO
      xml:
          tag_change:
            - ['.//controllers', '__CONTROLLER__', 'bitd_dpo_controller']
      graphs_inherit:
        - *base_graphs
        - *DPO_graphs
      graphs: &BITD_DPO_graphs
        - LN_cache_util
        - LN_cache_lifecycle
        - LN_cache_acq
        - LN_d1_task_exec
        - LN_d1_task_dist
        - LN_generalist_tab
    - name: BITD_ODPO
      xml:
        attr_change:
          - ['.//oracle_manager/tasking_oracle', 'task_exec_est', 'true' ]
          - ['.//oracle_manager/tasking_oracle', 'task_interface_est', 'true' ]
        tag_change:
          - ['.//controllers', '__CONTROLLER__', 'bitd_odpo_controller']

      graphs_inherit:
        - *base_graphs
        - *DPO_graphs
        - *BITD_DPO_graphs
    - name: BITD_MDPO
      xml:
          tag_change:
            - ['.//controllers', '__CONTROLLER__', 'bitd_mdpo_controller']
      graphs_inherit:
        - *base_graphs
        - *DPO_graphs
        - *BITD_DPO_graphs
    - name: BITD_OMDPO
      xml:
          tag_change:
            - ['.//controllers', '__CONTROLLER__', 'bitd_omdpo_controller']
      graphs_inherit:
        - *base_graphs
        - *DPO_graphs
        - *BITD_DPO_graphs

d2:
  xml:
    attr_change:
      - ['.//loop_functions', 'label', 'd2_loop_functions']
      - ['.//qt-opengl/user_functions', 'label', 'd2_qt_user_functions']
      - ['.//cache_sel_matrix/pickup_policy', 'policy', 'cache_size' ]
      - ['.//task_partition/src_sigmoid_sel/sigmoid_sel/sigmoid', 'gamma', '1.0' ]
      - ['.//task_partition/src_sigmoid_sel/sigmoid_sel/sigmoid', 'reactivity', '1.0' ]
      - ['.//subtask_sel/src_sigmoid_sel/sigmoid_sel/sigmoid', 'reactivity', '1.0' ]
      - ['.//subtask_sel/src_sigmoid_sel/sigmoid_sel/sigmoid', 'gamma', '1.0' ]

  controllers:
    - name: BIRTD_DPO
      xml:
        tag_change:
          - ['.//controllers', '__CONTROLLER__', 'birtd_dpo_controller']
      graphs_inherit:
        - *base_graphs
        - *DPO_graphs

      graphs: &BIRTD_DPO_graphs
        - LN_cache_util
        - LN_cache_lifecycle
        - LN_cache_acq
        - LN_cache_sites
        - LN_d1_task_exec
        - LN_d2_task_exec
        - LN_d2_task_dist
        - LN_harvester_tab
        - LN_collector_tab
        - LN_generalist_tab

    - name: BIRTD_ODPO
      xml:
        tag_change:
          - ['.//controllers', '__CONTROLLER__', 'birtd_odpo_controller']
          - ['.//oracle_manager/tasking_oracle', 'task_exec_est', 'true' ]
          - ['.//oracle_manager/tasking_oracle', 'task_interface_est', 'true' ]
      graphs_inherit:
        - *base_graphs
        - *DPO_graphs
        - *BIRTD_DPO_graphs

    - name: BIRTD_MDPO
      xml:
        tag_change:
          - ['.//controllers', '__CONTROLLER__', 'birtd_mdpo_controller']
      graphs_inherit:
        - *base_graphs
        - *DPO_graphs
        - *BIRTD_DPO_graphs

    - name: BIRTD_OMDPO
      xml:
        tag_change:
          - ['.//controllers', '__CONTROLLER__', 'birtd_omdpo_controller']
      graphs_inherit:
        - *base_graphs
        - *DPO_graphs
        - *BIRTD_DPO_graphs
