sierra:
  run:
    run_metrics_leaf: 'metrics'

  perf: 'perf.yaml'

ros:
  robots:
    turtlebot3:
      # pkg: "turtlebot3_gazebo"
      # model: "turtlebot3"
      prefix: "etb3_"
      # model_variant: "burger"
      setup_script: "$HOME/setup.bash"
